/* eslint-disable @next/next/no-img-element */
import type { NextPage } from "next";
import Head from "next/head";
import Script from "next/script";
import { useEffect, useState } from "react";
import Loader from "../components/Loader";
import PageLayout from "../layout/PageLayout/PageLayout";

const Home: NextPage = () => {
  const [load, setLoad] = useState(true);
  useEffect(() => {
    const run =()=> {
      setInterval(() => {
        setLoad(false);
      }, 3500);
    }
    run()
  }, []);

  return (
    <div>
      <Head>
        <title>Enjoy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1"
          crossOrigin="anonymous"
        />

        <link
          href="https://unpkg.com/aos@2.3.1/dist/aos.css"
          rel="stylesheet"
        />
      </Head>

      <Script src="https://unpkg.com/aos@2.3.1/dist/aos.js" />

      <Script
        src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW"
        crossOrigin="anonymous"
      />

      {load ? <Loader /> : <PageLayout />}
    </div>
  );
};

export default Home;
